In [67]:
""" 
print() function
"""


print("Hello world!")
print(100)
pi = 3.14
print(pi)

Hello world!
100
3.14


In [68]:
intro = "My name is"
name = "Geum Cheol"
print(intro + name)

My name isGeum Cheol


In [69]:
"""
Variables
"""

user_name = "Geum Cheol"
user_id = 201755012
user_email = "kja6023@hs.ac.kr"
is_student = True

#실습

In [70]:
# Declare and Initialize a variable
x = 1
print('x = ' , x)
print("Address of x: ", id(x))

#(Re)Assign a value to the variable
x = 2
print('x = ' , x)
print("Address of x: ", id(x))



x =  1
Address of x:  140717397845808
x =  2
Address of x:  140717397845840


In [71]:
# Valid cases:
myvar = "Shin"
my_var = "Shin"
_my_var = "Shin"
myVar = "Shin"
MYVAR = "Shin"
myvar2 = "Shin"

In [72]:
"""
Data Types: Integers
"""

chairs = 7
tables = 1
smartphone = 5
sofas = 1
broken_chairs = -1

#실습

In [73]:
"""
Data Types: Real Numbers
"""

PI = 3.14
Kospi_index = 3125.76
Krw_usd_exhange = 1176.83
Kosdaq_index =  1035.66

#실습 본인이 알고 있는 실수를 변수로 정의

In [74]:
"""
Data Types: Strings
"""

favorite_color = "Black"
favorite_game =  "Genshin"
favorite_sport = "Baseball"


#실습 본인이 좋아하는 것들을 문자열 변수로 정의

In [75]:
"""
Plus-Equals Operations
"""

a = 8
a *= 2
print(a)

16


In [76]:
"""
Erros
"""

#Name Erros


my_school = "HSU"
print(my_school)

HSU


In [77]:
is_tested = True
print(type(is_tested)) # 변수가 어떤 데이터 타입인지를 알려주는 함수


<class 'bool'>


In [78]:
# 1
print("Yes" == 'Yes')

# 2
print((2 > 1) == (5 < 10))

# 3
c = '2'
d = 2
print(c == d)


True
True
False


In [79]:
"""
conditional statements
"""

puppy = "maltepoo"
is_yes = False

if puppy == "maltese":
    is_yes = True
    print("말티즈가 맞습니다.")

elif puppy == "poodle":
    is_yes = True
    print("푸들이 맞습니다.")
    
print(is_yes)

False


In [80]:
"Exception Handling"

x = 1

try:
    print(y)
    print(x)
except:
    print('[Error]')

print("continue...")

[Error]
continue...


In [81]:
#리스트 소수
"""
Lists
"""
primes = [2,3,5,7,11,2]
print(primes)

empty_list = []
print(empty_list)

[2, 3, 5, 7, 11, 2]
[]


In [2]:
"""
Multiple differnet data types
"""
mixed =['Jenny', 1, 1.4, True]
print(mixed)
list_of_lists = [ ['a', 1],['b', 2] ]

['Jenny', 1, 1.4, True]


In [83]:
"""
Zero-indexing
"""

names = ['Roger','Rafael','Andy','Novak']

print(names[0]) #first data
print(names[1])
print(names[2])
print(names[3])

Roger
Rafael
Andy
Novak


In [84]:
"""
Negative indexing
"""
print(names[-1]) #last data
print(names[-2]) #second to last data
print(names[-3]) #third to last data
print(names[-4])

Novak
Andy
Rafael
Roger


In [85]:
#인덱스 구간에 있는 값을 구하는 방법
"""
List slicing
"""
hsu_buildings = ['만우관', '장공관', '필헌관', '소통관', '송암관', '늦봄관', '장준하통일관']
building_slice = hsu_buildings[1:4] #독립적인 객체
building_slice[0] = '생활관'

print(building_slice)
print(hsu_buildings)
print(hsu_buildings[:])

['생활관', '필헌관', '소통관']
['만우관', '장공관', '필헌관', '소통관', '송암관', '늦봄관', '장준하통일관']
['만우관', '장공관', '필헌관', '소통관', '송암관', '늦봄관', '장준하통일관']


In [86]:
"""
Multi-dimensinal Lists
"""

foodstore = [['해우리', '청정원', '맥도날드'], ['짜장명가', ' 중식', '중화비빔밥'], ['찌개동아리', '한식', '제육전골'], ['맘스터치', '양식', '싸이버거']]

print(foodstore)

foodstore[0][2] = '해우라면'
print(foodstore[0])

[['해우리', '청정원', '맥도날드'], ['짜장명가', ' 중식', '중화비빔밥'], ['찌개동아리', '한식', '제육전골'], ['맘스터치', '양식', '싸이버거']]
['해우리', '청정원', '해우라면']


In [87]:
"""

Adding Lists Together
"""
items_one = ['cake', 'cookie', 'bread']
items_two = ['biscuit', 'tart']

total_items = items_one + items_two
print(total_items)

['cake', 'cookie', 'bread', 'biscuit', 'tart']


In [88]:
"""
Useful Methods for Lists
"""

# Len()
knapsack = [2, 4, 3, 7, 10]
size = len(knapsack)
print(size)

5


In [89]:
# append()
orders = ['daisies', 'periwinkle']
orders.append('tulips')

print(orders)

['daisies', 'periwinkle', 'tulips']


In [90]:
# insert()
store_line = ['Karla', 'Maxium', 'Martin', 'Isabella']
store_line.insert(2, 'Vikor')

print(store_line)

['Karla', 'Maxium', 'Vikor', 'Martin', 'Isabella']


In [91]:
# pop()

sw_subjects = ['C Programming', 'Calculus', 'Data Engineering', 'Data Structures', 'Machine Learning']
sw_subjects.pop(2)




'Data Engineering'

In [92]:
sw_subjects = ['C Programming', 'Calculus', 'Data Engineering', 'Data Structures', 'Machine Learning']
sw_subjects.remove('Calculus')
print(sw_subjects)

['C Programming', 'Data Engineering', 'Data Structures', 'Machine Learning']


In [93]:
# Error
sw_subjects = ['C Programming', 'Calculus', 'Data Engineering', 'Data Structures', 'Machine Learning']
sw_subjects.remove('Algorithms')
print(sw_subjects)

ValueError: list.remove(x): x not in list

In [ ]:
# sort()

numbers = [4, 2, 1, 3]
numbers.sort()
print(numbers)



In [ ]:
hsu_buildings = ['만우관', '장공관', '필헌관', '소통관', '송암관', '늦봄관', '장준하통일관']
hsu_buildings.sort()

print(hsu_buildings)

In [ ]:
# sorted()

numbers = [4, 2, 1, 3]
sorted_numbers = sorted(numbers)
print(sorted_numbers)

In [ ]:
"""
for Loops
"""
nums = [1, 2, 3, 4, 5]
for num in nums:
    print(num)
    
# range()
for i in range(4):
    print(i)

In [ ]:
"""
continue Keyword
"""
nums = [1, 2, -1, 4, -5, 5, 2, -9]

for num in nums:
    # If num is negative, we skip it
    if num < 0:
        continue
    print(num)
   

In [ ]:
"""
break Keyword
"""

game_plays = ['stage1', 'stage2', 'stage3', 'gameover', 'stage4']

for play in game_plays:
    
    if play == 'gameover':
        print("Game is over...")
        break
     
    print(play + " is complete.")

In [ ]:
"""
List Comprehnesion
"""

one_to_ten = [i+1 for i in range(10)]
print (one_to_ten)


In [ ]:
"""
List comprehension including conditions
"""

hotspurs = [['손흥민', 'A+'], ['케인', 'F'],['돔벨레', 'F'], ['알리', 'F'],
            ['모우라', 'B+'], ['호이비에르','D']]
poors = [player[0] for player in hotspurs if player[1] == 'F']
print(poors)

In [ ]:
"""
Nested Loops
"""

one_to_nine = [i+1 for i in range(9)]

for i in one_to_nine:
    for j in one_to_nine:
        print("%d x %d = %d" % (i, j, i*j))

In [ ]:
# Infinite Loop
x = 1
y = 1
while x < 5:
    print("Do somthing")
    y +=1
    if y > 5:
        print("why doesn't it end?")

In [1]:
"""
Functions vs method
"""
#functions

def my_function(x):
    return x+1
y = 2
result =my_function(y)
print(result)

#method

class my_class:
    def my_method(self):
        return x+1
    
cls = my_class()
cls.my_method()

3


NameError: name 'x' is not defined

In [ ]:
""" #실습 참고
Function Parameters
"""
def introduce_myself(name, birthyear, city): #parameter
    print("Hello everyone, MY name is %s, I was born in %d, and I live in %s"
    % (name, birthyear, city))
introduce_myself("Hyun Ahn", 1985, "Anyang") #ar



In [ ]:
"""
Return Keyword
"""

# Leap year = 윤년 (2월 29일)
def check_leap_year(year):
    if year % 6 == 0:
        return "%s is a leap year." % (year)
    else:
        return "%s is not a leap year." % (year)
check_leap_year(2021)

In [ ]:
"""
Returning Multiple Values
"""


def square_point(x, y, z):
    x_squared = x ** 2
    y_squared = y ** 2
    z_squared = z ** 2
    return x_squared, y_squared, z_squared
three_squared, four_squared, five_squared = square_point(3, 4, 5)

print(three_squared, four_squared, five_squared)

In [ ]:
"""
Global variables
"""

a = "Hello"

def prints_a():
    print(a)
    
prints_a()

In [ ]:
"""
Local Variables
"""

def f1():
    a = 2 # local var.
    print(c)
f1()
print(c)

In [ ]:
"""
Keyworld Arguments and Default Valuves
"""
def findvolume(height, width, depth):
    print("Height = %s" % (height))
    print("Width = %s" % (width))
    print("Depth = %s" % (depth))
    return height * width * depth
#EX: height = 3, width = 1, depth = 2
print(findvolume(height=3, depth=2, width=1 ))

In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [3]:
# Creating a NumPy Array
lst = [1, 2, 3, 4]

arr = np.array(lst)
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
# .dtype attribut
print(arr.dtype)
lst = [1.1, 1.2, 2.5]

int32


In [5]:
arr = np.array([1.1, 1.2, 2.5])
print(arr.dtype)

float64


In [6]:
"""
Size Comparison of ndarray and list objects
"""

from sys import getsizeof

lst = []
print(getsizeof(lst))

arr = np.array([])
print(getsizeof(arr))

56
104


In [7]:
"""
Operations with Numpy arrays
"""

prices = [30, 25, 40, 20, 20, 35, 50, 35]
price_arr = np.array(prices)
#With a list
new_prices = [price -5 for price in prices]
print(new_prices)

price_arr -=5
print(price_arr)

[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [8]:
# Exercise: Operation with Test Scores
"""
Exercise: Test Scores
"""
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90 ,92])

test_3_fixed = test_3 +2
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

final_grade = total_grade /3
print(final_grade)

student_scores = np.array([test_1, test_2, test_3_fixed])
print(student_scores)

jeremy_test_2 = student_scores[1,3]
print(jeremy_test_2)

manual_adwoa_test_1 = np.array([student_scores[0, 1], student_scores[0, 2]])
print(manual_adwoa_test_1)

print(student_scores[:, 4])

[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 89  87  74  92  94]]
93
[94 88]
[87 91 94]


In [9]:
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
mask = a > 5
print(mask)

# select using logical operations 
selected = a[a > 5]
print(selected)
# combined logical operations
selected = a[(a > 5) & a < 4]
print(selected)

selected = a[(a > 4) & (a < 7)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  4  5  3  9  8  9  7]
[5]


In [10]:
# Exercise: Goldilocks Porridge Festival



In [11]:
"""

"""
#
print(np.arange(3))
print(np.arange(3, 9))
print(np.arange(3, 9, 1))

[0 1 2]
[3 4 5 6 7 8]
[3 4 5 6 7 8]


In [12]:
# Radoom number generator

np.random.seed(0)
arr1 = np.random.randint(10, size=(5, 6))
print(arr1)

[[5 0 3 3 7 9]
 [3 5 2 4 7 6]
 [8 8 1 6 7 7]
 [8 1 5 9 8 9]
 [4 3 0 3 5 0]]


In [13]:
# Attributes

np.random.seed(1)
arr = np.random.randint(10, size=(3, 4))
print(arr)

print("arr.ndim =", arr.ndim)
print("arr.shape =", arr.shape)
print("arr.size =", arr.size)
print("arr.dtype =", arr.dtype)
print("arr.itemsize =", arr.itemsize)
print("arr.nbytes =", arr.nbytes)



[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
arr.ndim = 2
arr.shape = (3, 4)
arr.size = 12
arr.dtype = int32
arr.itemsize = 4
arr.nbytes = 48


In [20]:
"""
Slicing
"""
arr = np.arange(10)
print(arr)

print(arr[3:7])
print(arr[:5])
print(arr[5:])
print(arr[::3])
print(arr[2:8:2])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 3 6 9]
[2 4 6]


In [22]:
# Multi-dimensional subarrays
np.random.seed(2)
arr = np.random.randint(10, size=(6, 8))
print(arr)
arr_sub = arr[:2, :2]
print(arr_sub)

arr_sub[0, 0] = 99
print(arr_sub)

[[8 8 6 2 8 7 2 1]
 [5 4 4 5 7 3 6 4]
 [3 7 6 1 3 5 8 4]
 [6 3 9 2 0 4 2 4]
 [1 7 8 2 9 8 7 1]
 [6 8 5 9 9 9 3 0]]
[[8 8]
 [5 4]]
[[99  8]
 [ 5  4]]


In [23]:
"""
Subarrays as no-copy views
"""

np.random.seed(2)
arr = np.random.randint(10, size=(6, 8))
print(arr)

arr_sub = arr[:2, :2].copy()
print(arr_sub)

arr_sub[0,0] = 99
print(arr_sub)

[[8 8 6 2 8 7 2 1]
 [5 4 4 5 7 3 6 4]
 [3 7 6 1 3 5 8 4]
 [6 3 9 2 0 4 2 4]
 [1 7 8 2 9 8 7 1]
 [6 8 5 9 9 9 3 0]]
[[8 8]
 [5 4]]
[[99  8]
 [ 5  4]]


In [29]:
"""
Reshaping of arr
"""

arr = np.arange(1, 10)
print(arr, '\n')

grid =arr.reshape(3, 3)
print(grid, '\n')

[1 2 3 4 5 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [30]:
# np. newaxi

In [36]:
"""
Array Concatenation
"""
# np.concatenate() , np.vstack(), np.hstack

arr_1 = np.array([[1, 2, 3], [1, 2, 3]])
arr_2 = np.array([[4, 5, 6], [4, 5, 6]])
arr_3 = np.array([[7, 8, 9], [7, 8, 9]])

arr_total = np.concatenate([arr_1, arr_2, arr_3], axis=1)
print(arr_total)

arr_total = np.vstack([arr_1, arr_2, arr_3])
print(arr_total)

arr_total = np.hstack([arr_1, arr_2, arr_3])
print(arr_total)

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


In [39]:
"""
Array Splitting
"""
arr = [1, 2, 3, 99, 99, 3, 2, 1]
print(arr, '\n')

arr_1, arr_2, arr_3 = np.split(arr, [3, 5])
print(arr_1, arr_2, arr_3)

[1, 2, 3, 99, 99, 3, 2, 1] 

[1 2 3] [99 99] [3 2 1]
